- nin.json
<pre align=center><img height=350 alt src="https://user-images.githubusercontent.com/578029/39932692-2074e460-5541-11e8-9a90-e5a0f4edea8a.png"></pre>
> Add super-early music draft

- res/graph.json
- src/squiggles.js
> Add squiggle prototype

- src/SceneSwitcherNode.js
- src/sleekAngles.js
> Add some geometries to sleekAngles scene

- src/squiggles.js
> Some basic iteration on squiggles

- res/graph.json
- src/SceneSwitcherNode.js
- src/ninjadevtext.js
> add ninjadev text gradient

- src/ninjadevtext.js
> Make first ninjadev gradient text white

- src/SceneSwitcherNode.js
- src/ninjadevtext.js
> Add some text animation

- src/bird.js
> Add dots behind bird

- res/graph.json
- src/SceneSwitcherNode.js
- src/shaders/sleekstadee/fragment.glsl
- src/shaders/sleekstadee/uniforms.json
- src/shaders/sleekstadee/vertex.glsl
- src/sleekstadeeNode.js
> Add some 3D

- res/graph.json
- src/SceneSwitcherNode.js
- src/WaveyPopNode.js
- src/shaders/WaveyPop/fragment.glsl
- src/shaders/WaveyPop/uniforms.json
- src/shaders/WaveyPop/vertex.glsl
> Add wavey pop effect

- src/sleekAngles.js
* plus
* half circle, filled
* half circle, stroked
* quarter circle, filled
* quarter circle, stroked
* squiggly line
* wavy squiggly
* rectangle/line
* star
* triangle
* hexagon
* filled square
The functions are not used anywhere yet
> Make functions for drawing various shapes for "90s art" particles:

- src/greetz.js
> Iterate on greets

- src/SceneSwitcherNode.js
- src/greetz.js
> Add more greets

- src/ParticleSystem.js
> Add a simple shadow to each particle

- src/SceneSwitcherNode.js
- src/WaveyPopNode.js
Waveypop dropped out of the demo by a merge accident. So I am reinstating it :)
> Reinstate waveypop effect

- src/cradle.js
> Fix timing of the cradle animation.

- res/graph.json
- src/ZentangleVisionShaderNode.js
- src/bgblue.js
- src/bgpants.js
- src/bgpink.js
- src/bgzigzag.js
- src/zentangleVision.js
> Add a few more effects for use as textures.

- src/shaders/sheipzidee/fragment.glsl
- src/shaders/sheipzidee/uniforms.json
> Iterate on 3d

- res/graph.json
- src/SceneSwitcherNode.js
> Moving things to roughly where we want them according to the document :)

- src/bgpants.js
- src/zentangleVision.js
> Animating the pants.

- src/discyblob.js
> Add prototype intro overlay

- src/sleekAngles.js
> Fire that lazor

- src/shaders/sheipzidee/fragment.glsl
- src/shaders/sheipzidee2/fragment.glsl
- src/sheipzideeNode.js
> Sheipspilt

- res/graph.json
- src/NinetiesPatternsNode.js
- src/shaders/yoyoCombiner/fragment.glsl
- src/shaders/yoyoCombiner/uniforms.json
- src/shaders/yoyoCombiner/vertex.glsl
- src/yoyo.js
- src/yoyoCombinerNode.js
> Use banana background in yoyo

- src/NinetiesPatternsNode.js
- src/shaders/NinetiesPatterns/fragment.glsl
- src/shaders/NinetiesPatterns/uniforms.json
- src/spinningCube.js
> Add transitions for ninities patterns

- src/arctic.js
- src/stars.js
> add shadow + rythm

- src/zentangleVision.js
So that we can know when they should be cool.
> ZentangleScene add number count timings

- src/zentangleVision.js
But keep old way in comments if we want to really quickly revert.
> Add movement for all numbers in count

- src/SceneSwitcherNode.js
- src/yoyo.js
> Add tunnel. Lacks transition from yolo and needs to be tweaked.

- src/ZentangleVisionShaderNode.js
- src/shaders/ZentangleVisionShader/fragment.glsl
- src/zentangleVision.js
Make sure that they are not shaded with the zentangle-pattern.
> Give numbers solid colors

- src/yoyo.js
> Add white circles. Tweak tunnel (not done yet)

- src/bgpants.js
> Make bgPants start more flashy

- src/sheipz.js
> Add pow particles to start of sheipz

- src/sleekAngles.js
- src/yoyo.js
> Add particles at the start of Dark 1

- src/yoyo.js
> Add shadow to the beat bar in yoyo

- src/sleekAngles.js
> Remove a tiny triangle that should not be there in the 1st 1234 transition

- src/introNode.js
This is so that we may start zooming in to transition to the next scene.
> Make tree stop growing at certain point
